### PR TITLE
Make `--derive` more flexible

### LINKED ISSUE #231: Should enums always implement PartialEq, Eq, PartialOrd, Ord?
Are there any examples where it doesn't make sense to derive these traits for an enum?

In my case I need to compare enums generated by Kopium, but specifying the derives using `--derive` flag does not work because of externally defined structures like `Condition`.

---

I've implemented my take on this here https://github.com/MathiasPius/kopium

### PR DESCRIPTION
**Pull request by MathiasPius**
Fixes #231 

This overhauls the `--derive` flag in a backwards compatible way, allowing users to specify traits to derive on a per-object basis, on all structs, all enums, or just [unit-only](https://doc.rust-lang.org/reference/items/enumerations.html) enums.

From the updated help text:

>  -D, --derive <DERIVE>
>
>  Derive these additional traits on generated objects
>  
>  There are three different ways of specifying traits to derive:
>  
>  1. A plain trait name will implement the trait for *all* objects generated from the custom resource definition: `--derive PartialEq`
>  
>  2. Constraining the derivation to a singular struct or enum: `--derive IssuerAcmeSolversDns01CnameStrategy=PartialEq`
>  
>  3. Constraining the derivation to only structs (`@struct`), enums (`@enum`) or *unit-only* enums (`@enum:simple`), meaning enums where no variants are tuple or structs: `--derive @struct=PartialEq`, `--derive @enum=PartialEq`, `--derive @enum:simple=PartialEq`
>  
>  See also: https://doc.rust-lang.org/reference/items/enumerations.html

I'm still not entirely sure if the `enum:simple` syntax is the right way to go. I experimented with inverting it so `enum` matched only the simple enums, and you had to do `enum+complex` to trigger derivation for complex types, but that was even less intuitive since you would expect `enum` to cover all enums by default.

### CODE REVIEW

**Comment by MathiasPius** [comment]
Seem to have lost some code during a rebase, hang tight!

**Comment by MathiasPius** [comment]
That should do it. Let me know what you think!

File: src/main.rs [hunk 1]
```diff
@@ -320,24 +411,46 @@ impl Kopium {
     }
 
     fn print_derives(&self, s: &Container) {
-        let mut derives = vec!["Serialize", "Deserialize", "Clone", "Debug"];
+        let mut derives: Vec<String> = ["Serialize", "Deserialize", "Clone", "Debug"]
+            .into_iter()
+            .map(String::from)
+            .collect();
```
Comment (clux) [inline src/main.rs:417]: hah. my refactor lasted one day :D

File: src/main.rs [hunk 2]
```diff
@@ -320,24 +411,46 @@ impl Kopium {
...
             }
-            derives.push(d);
+
+            // Only insert the trait if the target matches our container.
+            if let Some(derived_trait) = match &derive.target {
+                DeriveTarget::All => Some(&derive.derived_trait),
+                DeriveTarget::Type(name) => (&s.name == name).then_some(&derive.derived_trait),
+                DeriveTarget::Structs => s.is_enum.then_some(&derive.derived_trait),
+                DeriveTarget::Enums { unit_only } => {
+                    if s.is_enum && (!unit_only || s.members.iter().all(|member| member.type_.is_empty())) {
```
Comment (clux) [inline src/main.rs:441]: This possibly feels like it should be a helper on `Container` (but larger comment on that in main review body)

File: src/main.rs [hunk 3]
```diff
@@ -150,6 +169,78 @@ fn get_stdin_data() -> Result<String> {
...
+impl Derive {
+    pub fn all(derived_trait: &str) -> Self {
+        Derive {
+            target: DeriveTarget::All,
+            derived_trait: derived_trait.to_owned(),
+        }
+    }
+}
+
+fn parse_derive(arg: &str) -> Result<Derive> {
```
Comment (clux) [inline src/main.rs:207]: this could be an `impl FromStr for Derive`

File: src/main.rs [hunk 4]
```diff
@@ -150,6 +169,78 @@ fn get_stdin_data() -> Result<String> {
...
+
+        if derived_trait.is_empty() {
+            return Err(anyhow!("derived trait cannot be empty in '{arg}'"));
+        }
+
+        let target = if let Some(target) = target.strip_prefix('@') {
+            match target {
+                "struct" | "structs" => DeriveTarget::Structs,
+                "enum" | "enums" => DeriveTarget::Enums { unit_only: false },
+                "enum:simple" | "enums:simple" => DeriveTarget::Enums { unit_only: true },
```
Comment (clux) [inline src/main.rs:221]: minor nit: you allow plural but only document singular. maybe singular is enough?

File: src/main.rs [hunk 5]
```diff
@@ -150,6 +169,78 @@ fn get_stdin_data() -> Result<String> {
     Ok(input)
 }
 
+/// Target object for which the trait must be derived.
+#[derive(Debug, Clone, PartialEq)]
+enum DeriveTarget {
+    /// Derive the trait for all types
+    All,
+    /// Derive the trait for a specific type only.
```
Comment (clux) [inline src/main.rs:177]:
```suggestion
    /// Derive the trait for a named type only.
```

**Review by clux — COMMENTED** [review]
I think this looks great. Thanks a lot for doing this! I see nothing major implementation-wise here i disagree with. Some minor nits inlined (that are largely ignoreable).

One point on maintainability though; tests for this would be helpful. I also think this is self-contained enough that it could live inside a `derive.rs` module that can be tested therein. That way the only part from this that really __needs to__ live inside of main.rs is the loop over `self.derive` that decides whether `s` gets derives (and even that can possibly also be parametrised inside the `derive` module by passing the `s` by ref in there, but that's just a stray thought).

LMK what you think.

File: src/main.rs (hunk 4 above)
Comment (MathiasPius) [reply src/main.rs:221]: I just found myself alternating between singular and plural so figured I might as well make it lenient :)

File: src/main.rs (hunk 3 above)
Comment (MathiasPius) [reply src/main.rs:207]: Well spotted, should be an easy fix.

**Comment by MathiasPius** [comment]
> I think this looks great. Thanks a lot for doing this! I see nothing major implementation-wise here i disagree with. Some minor nits inlined (that are largely ignoreable).
> 
> One point on maintainability though; tests for this would be helpful. I also think this is self-contained enough that it could live inside a `derive.rs` module that can be tested therein. That way the only part from this that really **needs to** live inside of main.rs is the loop over `self.derive` that decides whether `s` gets derives (and even that can possibly also be parametrised inside the `derive` module by passing the `s` by ref in there, but that's just a stray thought).
> 
> LMK what you think.

Putting it in its own module makes a lot of sense, I avoided doing it because the rest of the project seemed to favor localized code over modularization. I'll try and extract it and see how testability can be written into it.

**Comment by MathiasPius** [comment]
I think that should be it!

File: src/derive.rs [hunk 6]
```diff
@@ -0,0 +1,239 @@
+use anyhow::anyhow;
+use std::str::FromStr;
+
+use crate::Container;
+
+/// Target object for which the trait must be derived.
+#[derive(Debug, Clone, PartialEq)]
+pub enum DeriveTarget {
```
Comment (clux) [inline src/derive.rs:8]: can technically be private now
```suggestion
/// Target object for which the trait must be derived.
#[derive(Debug, Clone, PartialEq)]
enum Target {
```

File: src/derive.rs [hunk 7]
```diff
@@ -0,0 +1,239 @@
...
+
+    let named_struct_trait = Derive {
+        target: DeriveTarget::Type("MyStruct".to_string()),
+        derived_trait: "PartialEq".to_string(),
+    };
+    assert!(!named_struct_trait.is_applicable_to(&simple_enum));
+    assert!(!named_struct_trait.is_applicable_to(&complex_enum));
+    assert!(!named_struct_trait.is_applicable_to(&structure));
+    assert!(named_struct_trait.is_applicable_to(&named_structure));
+    assert!(!named_struct_trait.is_applicable_to(&named_enum));
```
Comment (clux) [inline src/derive.rs:197]: great tests :+1:

**Review by clux — APPROVED** [review]
Very clean and separated now. Thanks a lot. I'll leave it here for a day just in case in case anyone else likes to chime in (also left an optional nit) but this is very simple to reason with now and happy to just send this out as is.

File: src/main.rs [hunk 8]
```diff
@@ -321,23 +340,28 @@ impl Kopium {
...
                 // Need to drop Default from enum as this cannot be derived.
                 // Enum defaults need to either be manually derived
                 // or we can insert enum defaults
                 continue;
             }
-            derives.push(d);
+
+            if derive.is_applicable_to(s) && !derives.contains(&derive.derived_trait.as_str()) {
+                derives.push(&derive.derived_trait)
+            }
```
Comment (clux) [inline src/main.rs:362]: Very happy with how this reads now.
