### PR TITLE
Fix map of arrays

### LINKED ISSUE #360: Map of arrays inner type handling
It seems like the implementation for objects of arrays, as tested in the `service_monitor_params` is invalid.

A schema like this:

```yaml
properties:
  endpoints:
    items:
      description: Endpoint defines a scrapeable endpoint serving Prometheus
        metrics.
      properties:
        params:
          additionalProperties:
            items:
              type: string
            type: array
          description: Optional HTTP URL parameters
          type: object
      type: object
    type: array
required:
- endpoints
type: object
```

Should result in the `params` member having the type `Option<BTreeMap<String, Vec<String>>>` instead of `Option<BTreeMap<String, String>>`.

You can verify this using `kubectl explain podmonitor.spec.podMetricsEndpoints.params` after installing the latest release of the prometheus-operator crds in which this contruct is present.

```
podMetricsEndpoints.params
GROUP:      monitoring.coreos.com
KIND:       PodMonitor
VERSION:    v1

FIELD: params <map[string][]string>


DESCRIPTION:
    <empty>
```

This means that the test is invalid too.

The same issue seems present with other inner types as well.

### PR DESCRIPTION
**Pull request by ClemaX**
Attempt to fix #360 by reusing `array_recurse_for_type` for maps of arrays.

### CODE REVIEW

File: src/analyzer.rs [hunk 1]
```diff
@@ -634,7 +611,7 @@ mod test {
         // should have a member with a key to the map:
         let map = &root.members[0];
         assert_eq!(map.name, "validationsInfo");
-        assert_eq!(map.type_, "Option<BTreeMap<String, AgentValidationsInfo>>");
+        assert_eq!(map.type_, "Option<BTreeMap<String, Vec<AgentValidationsInfo>>>");
```
Comment (clux) [inline src/analyzer.rs:614]: double checked this to make sure, and [sure enough](https://www.redhat.com/en/blog/pxe-artifacts-in-red-hat-advanced-cluster-management-for-kubernetes), this was also wrong :+1:
