### PR TITLE
Fix array of arrays handling

### LINKED ISSUE #315: List of lists not becoming Option<Vec<Vec<String>>>
Sorry for the flood of bug reports, I'm trying my best to bring fixes along.  I'm reporting here that given a list of lists, it's doesn't render the correct type.

I will push up a PR that shows this, but I'm not sure how to solve :(

### PR DESCRIPTION
**Pull request by ClemaX**
Add missing `Vec<{}>` formatting to array of arrays type.
Fixes #315 .

Supersedes #316 .

### CODE REVIEW

File: src/analyzer.rs [hunk 1]
```diff
@@ -1402,4 +1405,33 @@ type: object
...
+
+        let structs = analyze(schema, "KubeadmConfig", Cfg::default()).unwrap().0;
+
+        let root = &structs[0];
+        assert_eq!(root.name, "KubeadmConfig");
+        assert_eq!(root.level, 0);
+
+        let map = &root.members[0];
+        assert_eq!(map.name, "mounts");
+        assert_eq!(map.type_, "Option<Vec<Vec<String>>>");
```
Comment (clux) [inline src/analyzer.rs:1435]: test makes sense based on the schema and as a sanity, it does seem to match what i [find in the wild for the crd](https://github.com/AdminTurnedDevOps/kubernetes-examples/blob/9d6e5c214b0a1ad18cacba8888605a239a4775aa/azure-capi/capi-azurekubeadm.yaml#L101-L103)

**Review by clux — APPROVED** [review]
thanks a lot, once again!

this one needs a rebase/conflict fix first now
