### PR TITLE
Fix `x-kubernetes-preserve-unknown-fields` with type `array`

### LINKED ISSUE #313: `apiextensionsv1.JSON` does not seem to be properly processed
I'm working with the following crate which relies on auto-generated objects using CRs:

https://github.com/capi-samples/cluster-api-rs

It seems like the `apiextensionsv1.JSON` type is being serialized in this way:

https://github.com/capi-samples/cluster-api-rs/blob/84fcaa691bbace352663a5fab60094656176283c/src/api/capi_clusterclass.rs#L731-L734

```rust
    /// enum is the list of valid values of the variable.
    /// NOTE: Can be set for all types.
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "enum")]
    pub r#enum: Option<Vec<BTreeMap<String, serde_json::Value>>>,
```

You can find the source code here:

https://github.com/kubernetes-sigs/cluster-api/blob/15ce36f9eec61be27ec96e1044c2c642ee0828f4/api/v1beta1/clusterclass_types.go#L605-L608

I believe it should be translated into `Option<Vec<serde_json.Value>`.

### PR DESCRIPTION
**Pull request by mnaser**
Closes #313

### CODE REVIEW

**Comment by mnaser** [comment]
I dropped my initial test and I believe I changed behaviour of a test that I don't think had the right expectation, a type array for preserve unknown fields feels like it should not be a BTreeMap in this case.

**Comment by clux** [comment]
> I dropped my initial test and I believe I changed behaviour of a test that I don't think had the right expectation, a type array for preserve unknown fields feels like it should not be a BTreeMap in this case.

yeah, i had the same concern.

File: src/analyzer.rs [hunk 1]
```diff
@@ -427,6 +427,9 @@ fn array_recurse_for_type(
         match items {
             JSONSchemaPropsOrArray::Schema(s) => {
                 if s.type_.is_none() && s.x_kubernetes_preserve_unknown_fields == Some(true) {
+                    if s.x_kubernetes_preserve_unknown_fields == Some(true) {
```
Comment (clux) [inline src/analyzer.rs:430]: this condition is always true given 429

File: src/analyzer.rs [hunk 2]
```diff
@@ -427,6 +427,9 @@ fn array_recurse_for_type(
...
+                        return Ok(("Vec<serde_json::Value>".into(), level));
+                    }
                     let map_type = cfg.map.name();
                     return Ok((format!("Vec<{}<String, serde_json::Value>>", map_type), level));
```
Comment (clux) [inline src/analyzer.rs:434]: wonder why i wrapped this in a map earlier. curious to see if it breaks any other tests.

File: src/analyzer.rs (hunk 1 above)
Comment (mnaser) [reply src/analyzer.rs:430]: ah, right.

File: src/analyzer.rs (hunk 2 above)
Comment (clux) [reply src/analyzer.rs:434]: although, that is a bit weird.. the test `array_of_preserve_unknown_objects` should be doing the same thing

Comment (clux) [reply src/analyzer.rs:434]: ah.. of course. that is the test you are changing.

**Review by clux — COMMENTED** [review]
I think this looks sensible. Thank you!

Looking at this and cross referencing with the previous PR, I think we probably ought to never map-wrap serde_json::Value for unknown fields. I see we do it in a few more places.

happy to merge on green dco/tests tomorrow :sleeping:

**Review by clux — APPROVED** [review]

**Comment by mnaser** [comment]
I'll squash my commits to make it easier than going over signing all the other commits :)

**Review by clux — APPROVED** [review]
